apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kanidm-data
  namespace: my-tenant-identity
  labels:
    backup.company-as-code.io/include: "true"
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: TEMPLATE_FAST_STORAGE_CLASS
  resources:
    requests:
      storage: 20Gi
