apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-tenant-forgejo
resources:
  - ../../../../applications/forgejo/base
patches:
  - target:
      group: ""
      version: v1
      kind: Namespace
      name: forgejo
    patch: |-
      - op: replace
        path: /metadata/name
        value: my-tenant-forgejo
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: forgejo
    patch: |-
      - op: replace
        path: /spec/chart/spec/sourceRef/namespace
        value: my-tenant-forgejo
