apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenant-my-tenant
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/tenants/my-tenant
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: dex
    - name: garage
    - name: minio-operator
    - name: postgresql-operator
    - name: mariadb-operator
    - name: nginx-ingress
    - name: external-dns
    - name: arc-controller
  timeout: 20m
  wait: true
