apiVersion: v1
kind: Service
metadata:
  name: garage-headless
  namespace: garage
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: garage
  ports:
    - name: s3
      port: 3900
    - name: rpc
      port: 3901
    - name: web
      port: 3902
    - name: admin
      port: 3903
---
apiVersion: v1
kind: Service
metadata:
  name: garage
  namespace: garage
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: garage
  ports:
    - name: s3
      port: 3900
      targetPort: s3
    - name: admin
      port: 3903
      targetPort: admin
