apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-tenant-matomo
resources:
  - ../../../../applications/matomo/base
patches:
  - path: namespace.patch.yaml
    target:
      version: v1
      kind: Namespace
      name: matomo
  - path: domain.patch.yaml
  - path: database.patch.yaml
  - path: storage.patch.yaml
