apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matomo-data
  namespace: matomo
spec:
  storageClassName: TEMPLATE_FAST_STORAGE_CLASS
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: matomo-mariadb
  namespace: matomo
spec:
  storage:
    storageClassName: TEMPLATE_FAST_STORAGE_CLASS
