apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vmware-tanzu
  namespace: velero
spec:
  interval: 1h
  url: https://vmware-tanzu.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 30m
  chart:
    spec:
      chart: velero
      version: 10.0.12
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
  values:
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.10.0
        volumeMounts:
          - mountPath: /target
            name: plugins
    credentials:
      useSecret: true
      name: velero-credentials
    configuration:
      defaultBackupStorageLocation: garage
      uploaderType: kopia
      defaultVolumesToFsBackup: true
      defaultBackupTTL: 720h
      features: EnableCSI
      backupStorageLocation:
        - name: garage
          provider: aws
          bucket: velero-backups
          default: true
          credential:
            name: velero-credentials
            key: garage
          config:
            region: garage
            s3ForcePathStyle: "true"
            s3Url: http://garage.garage.svc.cluster.local:3900
        - name: external-s3
          provider: aws
          bucket: TEMPLATE_EXTERNAL_BACKUP_BUCKET
          credential:
            name: velero-credentials
            key: external-s3
          config:
            region: TEMPLATE_EXTERNAL_BACKUP_REGION
            s3ForcePathStyle: "false"
            s3Url: https://s3.TEMPLATE_EXTERNAL_BACKUP_REGION.amazonaws.com
      volumeSnapshotLocation:
        - name: default
          provider: aws
          config:
            region: TEMPLATE_EXTERNAL_BACKUP_REGION
    schedules:
      daily-garage:
        disabled: false
        schedule: "0 2 * * *"
        template:
          ttl: 720h
          storageLocation: garage
          includedNamespaces: ["*"]
          excludedResources: [events, events.events.k8s.io]
      weekly-external-s3:
        disabled: false
        schedule: "0 1 * * 0"
        template:
          ttl: 2160h
          storageLocation: external-s3
          includedNamespaces: ["*"]
          labelSelector:
            matchLabels:
              backup.company-as-code.io/include: "true"
      monthly-external-s3:
        disabled: false
        schedule: "0 3 1 * *"
        template:
          ttl: 8760h
          storageLocation: external-s3
          includedNamespaces: ["*"]
    metrics:
      enabled: true
    deployNodeAgent: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    nodeAgent:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
