apiVersion: v1
kind: ConfigMap
metadata:
  name: infrastructure-config
  namespace: flux-system
data:
  cluster-name: my-cluster
  tenant-name: my-tenant
  base-domain: TEMPLATE_DOMAIN
  auth-domain: auth.TEMPLATE_DOMAIN
  idp-domain: idp.TEMPLATE_DOMAIN
  chat-domain: chat.TEMPLATE_DOMAIN
  todo-domain: todo.TEMPLATE_DOMAIN
  drive-domain: drive.TEMPLATE_DOMAIN
  git-domain: git.TEMPLATE_DOMAIN
  warden-domain: warden.TEMPLATE_DOMAIN
  analytics-domain: analytics.TEMPLATE_DOMAIN
  bifrost-domain: bifrost.TEMPLATE_DOMAIN
  context-domain: context.TEMPLATE_DOMAIN
  hermes-domain: hermes.TEMPLATE_DOMAIN
  observe-domain: observe.TEMPLATE_DOMAIN
  fast-storage-class: TEMPLATE_FAST_STORAGE_CLASS
  bulk-storage-class: TEMPLATE_BULK_STORAGE_CLASS
